## Slide 11: R AS A CALCULATOR

In [1]:
2+2

[1] 4

In [2]:
(2*5)+(12/3)-(2^3)

[1] 6

In [3]:
exp(log(1))

[1] 1

In [4]:
sqrt(25)

[1] 5

In [5]:
log(2*2)

[1] 1.386294

In [6]:
log(2)+log(2)

[1] 1.386294

## Slide 12: GETTING HELP

In [7]:
?plot

plot.default             package:graphics              R Documentation

_T_h_e _D_e_f_a_u_l_t _S_c_a_t_t_e_r_p_l_o_t _F_u_n_c_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     Draw a scatter plot with decorations such as axes and titles in
     the active graphics window.

_U_s_a_g_e:

     ## Default S3 method:
     plot(x, y = NULL, type = "p",  xlim = NULL, ylim = NULL,
          log = "", main = NULL, sub = NULL, xlab = NULL, ylab = NULL,
          ann = par("ann"), axes = TRUE, frame.plot = axes,
          panel.first = NULL, panel.last = NULL, asp = NA,
          xgap.axis = NA, ygap.axis = NA,
          ...)
     
_A_r_g_u_m_e_n_t_s:

    x, y: the 'x' and 'y' arguments provide the x and y coordinates for
          the plot.  Any reasonable way of defining the coordinates is
          acceptable.  See the function 'xy.coords' for details.  If
          supplied separately, they must be of the same length.

    type: 1-character string g

## Slide 13: ASSIGNING VALUES TO THE OBJECTS a AND A

In [8]:
a <- 2+5
A <- 10
ls()

[1] "A" "a"

## Slide 14:

Make a sequence

Here is a sequence from 0 up to 10

In [9]:
0:10

[1]  0  1  2  3  4  5  6  7  8  9 10

Here is a sequence from 15 down to 5

In [10]:
15:5

[1] 15 14 13 12 11 10  9  8  7  6  5

sequence in steps other than 1

from, to, by

In [11]:
seq(from = 0, to = 1.2, by = 0.1)

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2

assigning sequence to object

In [12]:
x <- seq(from = 0, to = 1.5, length = 11); x

[1] 0.00 0.15 0.30 0.45 0.60 0.75 0.90 1.05 1.20 1.35 1.50

## Slide 15: generating repeats

In [13]:
rep(8, 5)

[1] 8 8 8 8 8

In [14]:
rep(1:4, each = 2)

[1] 1 1 2 2 3 3 4 4

In [15]:
rep(1:4, each = 2, times = 3)

[1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

## slide 16: functions in R

In [16]:
# a simple function
f<-function(x){x^2}; f(2)

[1] 4

In [17]:
# a function of two variables
f<-function(x,pow){x^pow}; f(2,2)

[1] 4

In [18]:
# a function with a default value.
f<-function(x,pow=2){x^pow}; f(2,2); f(2);f(2,3)

[1] 4

[1] 4

[1] 8

## slide 17: Some functions previously applies

In [19]:
"+"(2,2)

[1] 4

In [20]:
sqrt(25)

[1] 5

In [21]:
log(2)

[1] 0.6931472

In [22]:
ls()

[1] "A" "a" "f" "x"

In [23]:
":"(0,10)

[1]  0  1  2  3  4  5  6  7  8  9 10

In [24]:
seq(from=0.1,to=1.2,by=0.1)

[1] 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2

In [25]:
# look at
seq(0.1,1.2,0.1)

[1] 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2

and compare with the syntax from the help pages

In [26]:
rep(1:4,each=2,time=3)

[1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

## slide 18: Singles

In [27]:
TRUE
1==2
1
"5"
"abc"

[1] TRUE

[1] FALSE

[1] 1

[1] "5"

[1] "abc"

## slide 19: Vectors

In [28]:
# vector of numbers
c(1,1.2,pi,exp(1))

# vector of logicals
c(TRUE,1==2)

# vector of characters
c("a","ab","abc")

# combination
c("a",5,1==2)

[1] 1.000000 1.200000 3.141593 2.718282

[1]  TRUE FALSE

[1] "a"   "ab"  "abc"

[1] "a"     "5"     "FALSE"

## Slide 20: Matrices

In [29]:
# matrix of numbers
matrix(c(1,2,3,4,5,6)+pi,nrow=2)

# matrix of logicals
matrix(c(1,2,3,4,5,6)+pi,nrow=2)<6

[,1]     [,2]     [,3]    
[1,] 4.141593 6.141593 8.141593
[2,] 5.141593 7.141593 9.141593

[,1] [,2]  [,3] 
[1,] TRUE FALSE FALSE
[2,] TRUE FALSE FALSE

## slide 21: Data frames

In [30]:
data.frame(treatment=c("active","active","placebo"),
            bp=c(80,85,90))

# same data placed in a matrix
cbind(treatment=c("active","active","placebo"),bp=c(80,85,90))

treatment bp
1 active    80
2 active    85
3 placebo   90

treatment bp
[1,] active    80
[2,] active    85
[3,] placebo   90

## slide 22: Lists

In [31]:
list(a=1,b="abc",c=c(1,2,3),d=list(e=matrix(1:4,2), f=function(x){x^2}))

$a
[1] 1

$b
[1] "abc"

$c
[1] 1 2 3

$d
$d$e
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$d$f
function (x) 
{
    x^2
}

## Slide 24: Setting the working directory.

In [32]:
#setwd("C:/<your favorite directory using slashes for separation>")
# remove the hashtag for execution when you have entered your favorite directory
# example : setwd("C:/projects/my project name/R analysis number 3/messy data")
getwd()

[1] "/Users/dittegilsfeldt/Documents/DTU_GitHub/DTU_Human-Centered_Artificial_Intelligence_MSc/MSc__7_Semester__Overgangssemester/02409__Multivariare_Statistics/Lecture_Notes"